name: URL Check

on:
  push:
    branches:
      - 'main'
  schedule:
    # Run at 00:00 on the first day of the month
    - cron: '0 0 1 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 10
    name: check URLs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: .tool-versions
        cache: pnpm
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: CheckURL
      run: pnpm test:url
